[versions]
android-plugin = "8.3.1"
dependencyAnalysis = "1.33.0"
dependencySorter = "0.8"
githubRelease = "2.5.2"
gradleDoctor = "0.10.0"
kotlin = "2.0.10"
mavenPublish = "0.29.0"
reckon = "0.18.3"

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
gradlePlugin-dependencyAnalysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }
gradlePlugin-doctor = { module = "com.osacky.doctor:doctor-plugin", version.ref = "gradleDoctor" }
gradlePlugin-githubRelease = { module = "com.github.breadmoirai:github-release", version.ref = "githubRelease" }
gradlePlugin-gradleAndroidCacheFix = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin:3.0.1"
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish" }
gradlePlugin-reckon = { module = "org.ajoberstar.reckon:reckon-gradle", version.ref = "reckon" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

[plugins]
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
dependencySorter = { id = "com.squareup.sort-dependencies", version.ref = "dependencySorter" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
gradleDoctor = { id = "com.osacky.doctor", version.ref = "gradleDoctor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckon" }
